### ISSUE TITLE
Visualisation issue

### ISSUE THREAD

**Issue by DunapackMS** [wolfrage76/Subspace-Thingies#50]
With the latest CLI version, the visualisation of the plots/miner is no longer working. It shows only the wins.

![cli](https://github.com/user-attachments/assets/04d246d4-4abd-4528-b880-8be2b5b91db6)

**Comment by wormcoffee** [comment]
This issue has been occurring since the farmer was updated to ver Jul-16, and it should be due to log format changed.

**Comment by wolfrage76** [comment]
Sorry gang, been insanely busy with home and work -- I am upgrading versions now and will get a fix out ASAP.

**Comment by wolfrage76** [comment]
I'm still working on this, sorry gang! Mostly updated and fixing the display. and calc bugs for the new metric formats. Should be done soon!

**Comment by DunapackMS** [comment]
Take your time, we are calm and waiting :)

**Comment by wolfrage76** [comment]
Please try the latest release and let me know if you have any issues with it
